
FROM arm64v8/golang:1.20

WORKDIR /app

COPY go.* ./
RUN go mod download


COPY . ./
RUN go mod tidy
RUN go build -v -o bin/ all 


EXPOSE 8080

ENV PORT=8080
ENV PROTO_ENDPOINT=togo-proto:8081

CMD ["sh", "-c", "bin/json_handler -port=${PORT} -proto-endpoint=${PROTO_ENDPOINT}"]
