FROM golang:1.20 AS build

WORKDIR /app

COPY go.* ./
RUN go mod download


COPY . ./
RUN go mod tidy
RUN go build -v -o bin/ all 

FROM rockylinux:9 AS final


WORKDIR /app

COPY --from=build /app/bin/proto_handler bin/proto_handler


EXPOSE 8081

CMD [ "/app/bin/proto_handler" ]
