FROM golang:1.20 AS build

WORKDIR /app

COPY go.* ./
RUN go mod download


COPY . ./
RUN go mod tidy
RUN go build -v -o bin/ all 

FROM rockylinux:9 AS final

WORKDIR /app

COPY --from=build /app/bin/json_handler /app/bin/json_handler

EXPOSE 8080

ENV PORT=8080
ENV PROTO_ENDPOINT=proto-handler:8081

CMD ["sh", "-c", "/app/bin/json_handler -port=${PORT} -proto-endpoint=${PROTO_ENDPOINT}"]
